"""
Master Report Generator - CAD/CAM Quadruped Robot
Generates: Project_Report_Dhruv_Khanna.pdf
Author: Dhruv Khanna
"""

import os
from fpdf import FPDF
from fpdf.enums import XPos, YPos
import numpy as np

OUT_DIR  = os.path.dirname(os.path.abspath(__file__))
REPORT   = os.path.join(OUT_DIR, 'Project_Report_Dhruv_Khanna.pdf')

# Image paths (generated by other scripts)
IMG = {
    'iso':      os.path.join(OUT_DIR, 'Q1_Q2_robot_isometric.png'),
    'front':    os.path.join(OUT_DIR, 'Q1_Q2_robot_front.png'),
    'side':     os.path.join(OUT_DIR, 'Q1_Q2_robot_side.png'),
    'top':      os.path.join(OUT_DIR, 'Q1_Q2_robot_top.png'),
    'joints':   os.path.join(OUT_DIR, 'Q3_joint_limits.png'),
    'motion':   os.path.join(OUT_DIR, 'Q4_motion_snapshot.png'),
    'gait':     os.path.join(OUT_DIR, 'Q5_gait_calculation.png'),
    'stability':os.path.join(OUT_DIR, 'Q6_stability_check.png'),
}


class PDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=18)

    # -- Header -----------------------------------------------------------------
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font('Helvetica', 'B', 8)
        self.set_text_color(100, 100, 140)
        self.cell(0, 6, 'CAD/CAM Quadruped Robot - Dhruv Khanna', align='L',
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(60, 60, 100)
        self.set_line_width(0.4)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(2)

    # -- Footer -----------------------------------------------------------------
    def footer(self):
        self.set_y(-14)
        self.set_font('Helvetica', '', 7)
        self.set_text_color(120, 120, 160)
        self.cell(0, 5, f'Page {self.page_no()}', align='C')

    # -- Section heading --------------------------------------------------------
    def section(self, title):
        self.ln(4)
        self.set_fill_color(30, 40, 80)
        self.set_text_color(100, 180, 255)
        self.set_font('Helvetica', 'B', 12)
        self.cell(0, 9, title, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(30, 30, 30)
        self.ln(2)

    def subsection(self, title):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(60, 100, 200)
        self.cell(0, 7, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(30, 30, 30)

    def body(self, text, size=9.5):
        self.set_font('Helvetica', '', size)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 5.5, text)
        self.ln(1)

    def kv(self, key, val):
        self.set_font('Helvetica', 'B', 9.5)
        self.set_text_color(40, 40, 40)
        self.cell(60, 6, key + ':', new_x=XPos.RIGHT, new_y=YPos.LAST)
        self.set_font('Helvetica', '', 9.5)
        self.cell(0, 6, val, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def add_image(self, path, caption='', w=170):
        if os.path.exists(path):
            self.ln(2)
            self.image(path, x=(self.w - w) / 2, w=w)
            if caption:
                self.set_font('Helvetica', 'I', 8)
                self.set_text_color(100, 100, 140)
                self.cell(0, 5, caption, align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.ln(3)
        else:
            self.body(f'[Image not found: {os.path.basename(path)}]')

    def table_row(self, cols, widths, bold=False, fill=False):
        if fill:
            self.set_fill_color(230, 235, 255)
        font = 'B' if bold else ''
        self.set_font('Helvetica', font, 8.5)
        self.set_text_color(30, 30, 30)
        for col, w in zip(cols, widths):
            self.cell(w, 6.5, col, border=1, fill=fill,
                      new_x=XPos.RIGHT, new_y=YPos.LAST)
        self.ln()


# ==============================================================================
# BUILD PDF
# ==============================================================================
pdf = PDF()
pdf.set_margins(18, 18, 18)

# -- Cover Page ----------------------------------------------------------------
pdf.add_page()
pdf.ln(20)

# Dark header banner
pdf.set_fill_color(13, 13, 26)
pdf.rect(0, 0, pdf.w, 70, 'F')
pdf.set_y(15)
pdf.set_font('Helvetica', 'B', 22)
pdf.set_text_color(100, 180, 255)
pdf.cell(0, 12, 'CAD/CAM QUADRUPED ROBOT', align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('Helvetica', '', 13)
pdf.set_text_color(170, 200, 255)
pdf.cell(0, 8, 'Design, Modeling, Simulation and Gait Analysis', align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('Helvetica', '', 10)
pdf.set_text_color(120, 140, 200)
pdf.cell(0, 7, 'Mini Project Report', align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

pdf.ln(30)
pdf.set_text_color(40, 40, 40)
pdf.set_font('Helvetica', 'B', 11)
pdf.cell(0, 8, 'Student Details', align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('Helvetica', '', 10)
details = [
    ('Name',           'Dhruv Khanna'),
    ('Student ID',     '12254732'),
    ('Course',         'CAD/CAM'),
    ('Assignment',     'Quadruped Robot Mini Project'),
    ('Date',           '16 August 2026'),
    ('Tools Used',     'Python 3.14, NumPy, Matplotlib, SciPy'),
]
for k, v in details:
    pdf.cell(80, 7, k + ':', align='R', new_x=XPos.RIGHT, new_y=YPos.LAST)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, '  ' + v, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font('Helvetica', '', 10)

pdf.ln(10)
pdf.set_fill_color(13, 13, 26)
pdf.set_text_color(100, 180, 255)
pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 8, 'Problem Statement', fill=True, align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('Helvetica', 'I', 9)
pdf.set_text_color(40, 40, 40)
pdf.multi_cell(0, 6, (
    '"Design a simplified quadruped robot and validate basic leg gait motion using CAD modeling, '
    'mathematical gait calculation, and simulation, focusing on correctness rather than complexity."'
))

pdf.ln(10)
pdf.set_text_color(80, 80, 120)
pdf.set_font('Helvetica', '', 9)
pdf.cell(0, 6, 'Contents: Q1 Structure Design  |  Q2 CAD Assembly  |  Q3 Joint Limits', align='C',
         new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.cell(0, 6, 'Q4 Motion Simulation  |  Q5 Gait Calculation  |  Q6 Stability  |  Q7 Limitations',
         align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)


# -- Q1: Mechanical Structure Design -------------------------------------------
pdf.add_page()
pdf.section('Question 1: Mechanical Structure Design')

pdf.body(
    'The quadruped robot is designed with a rectangular body frame and four identical legs, '
    'each having 2 degrees of freedom (DOF): a hip joint for fore-aft swing and a knee joint '
    'for flexion/extension. The design prioritises symmetry and simplicity.'
)

pdf.subsection('Body Frame Specifications')
pdf.kv('Body Length (X)', '200 mm')
pdf.kv('Body Width  (Y)', '120 mm')
pdf.kv('Body Height (Z)', '30 mm')
pdf.kv('Material (assumed)', 'Aluminium alloy 6061 (lightweight, rigid)')
pdf.kv('Number of Legs', '4 (Front-Left, Front-Right, Rear-Left, Rear-Right)')
pdf.kv('DOF per Leg', '2 (Hip + Knee)')
pdf.kv('Total Actuated DOF', '8')

pdf.ln(2)
pdf.subsection('Leg Link Dimensions')
pdf.kv('Thigh (upper link) length', '80 mm')
pdf.kv('Shin  (lower link) length', '70 mm')
pdf.kv('Total leg reach', '<= 150 mm (fully extended)')
pdf.kv('Hip attachment inset', '20 mm from body end (each side)')

pdf.add_image(IMG['iso'], 'Figure 1a - Isometric View of Quadruped Robot')
pdf.add_image(IMG['top'], 'Figure 1b - Top View showing body symmetry and leg positions', w=140)


# -- Q2: CAD Modeling and Assembly ---------------------------------------------
pdf.add_page()
pdf.section('Question 2: CAD Modeling and Assembly')

pdf.body(
    'All four legs are identical assemblies consisting of a thigh link, shin link, hip joint, '
    'and knee joint. They are attached to the four corners of the body frame using the mirroring '
    'technique: one leg is designed and then reflected across the longitudinal and lateral axes. '
    'This ensures perfect symmetry.'
)

pdf.subsection('Assembly Details')
pdf.kv('Front pair (FL, FR)', 'Mirrored about the X-axis (longitudinal symmetry)')
pdf.kv('Left pair (FL, RL)',  'Mirrored about the Y-axis (lateral symmetry)')
pdf.kv('Joint alignment',     'All hip joints lie on the same Z-plane (body bottom)')
pdf.kv('Collision check',     'No link overlap at any valid joint configuration')

pdf.ln(2)
pdf.body(
    'The figure below shows both the front and side views confirming correct leg symmetry and '
    'that all four feet reach the same ground plane in the neutral standing pose.'
)

pdf.add_image(IMG['front'], 'Figure 2a - Front View (leg symmetry visible)', w=130)
pdf.add_image(IMG['side'],  'Figure 2b - Side View (joint alignment visible)', w=130)


# -- Q3: Joint Definition ------------------------------------------------------
pdf.add_page()
pdf.section('Question 3: Joint Definition and Motion Limits')

pdf.body(
    'Each leg has two revolute joints. Both rotate about the Y-axis (lateral axis), '
    'producing motion in the sagittal plane (forward/backward and up/down). '
    'This 2-DOF configuration is sufficient for basic walking and trotting gaits on flat terrain.'
)

pdf.subsection('Joint Limit Table')
widths = [28, 28, 38, 90]
pdf.table_row(['Joint', 'Axis', 'Range', 'Justification'], widths, bold=True, fill=True)
pdf.table_row(['Hip',  'Y (lateral)', '-35 to +35 deg',
               'Clearance from body; prevents leg/body collision at extremes'], widths)
pdf.table_row(['Knee', 'Y (lateral)', '0 to -120 deg',
               'Biologically inspired; 0=fully extended, -120=deep flex; prevents hyperextension'],
              widths, fill=True)

pdf.ln(4)
pdf.body(
    'The hip limits of +/-35 degrees are sufficient for the target stride length at walking speed. '
    'Exceeding these would cause the leg to contact the body frame. '
    'The knee range of 0 to -120 degrees covers all required stance and swing configurations '
    'while preventing mechanical hyperextension.'
)

pdf.add_image(IMG['joints'], 'Figure 3 - Joint axes and swept ranges for hip and knee')


# -- Q4: Motion Validation -----------------------------------------------------
pdf.add_page()
pdf.section('Question 4: Motion Validation via Simulation')

pdf.body(
    'A single-leg kinematic simulation was performed by sweeping both joints through their '
    'respective ranges using sinusoidal profiles. The 2-DOF forward kinematics model was used '
    'to compute foot position at each frame. '
    'An animated GIF (Q4_motion_simulation.gif) showing the full motion sweep has been generated.'
)

pdf.subsection('Simulation Parameters')
pdf.kv('Hip profile',  'theta_hip(t) = 25 deg x sin(2*pi*t/T)  -> sweeps -25 to +25 deg')
pdf.kv('Knee profile', 'theta_knee(t) = -60 deg - 30 deg x sin(2*pi*t/T + pi)  -> -30 to -90 deg')
pdf.kv('Frames',       '72 frames per cycle (25 fps)')
pdf.kv('Duration',     '2 complete gait cycles shown')

pdf.ln(2)
pdf.body(
    'Observations from simulation:\n'
    '- No self-collision detected at any frame within the defined joint limits.\n'
    '- The foot traces a smooth elliptical arc, clearing the ground during swing.\n'
    '- The knee always remains in the valid range [0, -120 deg] throughout motion.\n'
    '- The overall motion is smooth and physically plausible.'
)

pdf.add_image(IMG['motion'],
              'Figure 4 - Motion snapshot: foot trajectory (dashed) and leg at 3 poses')


# -- Q5: Gait Cycle Calculation ------------------------------------------------
pdf.add_page()
pdf.section('Question 5: Gait Cycle Calculation')

pdf.subsection('Gait Type: Trot')
pdf.body(
    'A trot gait is used, where diagonal leg pairs move in synchrony. '
    'This is the most energy-efficient gait for moderate speeds and is widely used in '
    'quadruped robots (e.g., Boston Dynamics Spot).'
)

pdf.subsection('Gait Parameters')
pdf.kv('Stride Length (L)', '150 mm = 0.15 m  (selected based on leg geometry)')
pdf.kv('Walking Speed (v)', '0.30 m/s')
pdf.kv('Gait Cycle Time',   'T = L / v = 0.15 / 0.30 = 0.500 s  ->  f = 2.00 Hz')
pdf.kv('Duty Factor',       '0.5  (50% stance, 50% swing - typical for trot)')
pdf.kv('Stance Duration',   '0.5 x T = 0.5 x 0.500 = 250 ms')
pdf.kv('Swing Duration',    '(1 - 0.5) x T = 0.5 x 0.500 = 250 ms')

pdf.ln(3)
pdf.subsection('Phase Offsets')
pdf.body(
    'In a trot gait, diagonal leg pairs are 180 degrees out of phase:\n'
    '  FL (Front-Left) and RR (Rear-Right) : phase = 0 deg    (reference pair)\n'
    '  FR (Front-Right) and RL (Rear-Left) : phase = 180 deg  (offset by T/2 = 0.25 s)'
)

pdf.subsection('Joint Angle Profiles (One Leg - FL)')
pdf.kv('Hip  angle', 'theta_hip(t)  = A_hip x sin(2*pi*t/T)  where A_hip = 25 deg')
pdf.kv('Knee angle', 'theta_knee(t) = -60 deg - B x sin(2*pi*t/T + pi)  where B = 30 deg')
pdf.body(
    'The negative sign on the knee ensures it bends during swing (foot clearance) '
    'and extends during stance (load bearing).'
)

pdf.add_image(IMG['gait'], 'Figure 5 - Gait calculation: joint profiles, foot trajectory, and gait diagram')


# -- Q6: Stability Check -------------------------------------------------------
pdf.add_page()
pdf.section('Question 6: Stability Check')

pdf.body(
    'Static stability is evaluated using the Support Polygon Method: the robot is statically '
    'stable if and only if the vertical projection of its Centre of Mass (CoM) lies within the '
    'convex hull of its grounded foot positions.'
)

pdf.subsection('Centre of Mass (CoM) Location')
pdf.body(
    'Assuming uniform mass distribution in the body frame, the CoM projects to the geometric '
    'centre of the body: (0, 0) mm in the body XY frame.'
)

pdf.subsection('Stability Results')
widths2 = [55, 45, 45, 55]
pdf.table_row(['Configuration', 'Grounded Feet', 'CoM Inside?', 'Stability Margin'],
              widths2, bold=True, fill=True)
pdf.table_row(['Static Stand (4 feet)', '4', 'YES', '~60 mm'], widths2)
pdf.table_row(['Walk Gait - 1 foot lifted', '3', 'YES', '~28 mm'], widths2, fill=True)
pdf.table_row(['Trot Gait - 2 diagonal', '2', 'Dynamic phase', 'N/A (line support)'], widths2)

pdf.ln(3)
pdf.body(
    'The walk gait (3 feet always in contact) maintains static stability throughout the stride. '
    'The trot gait relies on dynamic stability - the forward momentum maintains balance during '
    'the single-support phase. This is physically realistic and is the standard operating '
    'mode for trotting quadrupeds.'
)

pdf.add_image(IMG['stability'], 'Figure 6 - Support polygon analysis for three cases')


# -- Q7: Design Limitations ----------------------------------------------------
pdf.add_page()
pdf.section('Question 7: Design Limitations')

pdf.subsection('Limitation 1: 2-DOF Legs Cannot Handle Lateral Terrain Variation')
pdf.body(
    'Each leg has only 2 DOF, both rotating about the sagittal (Y) axis. There is no '
    'abduction/adduction (side-to-side) DOF. As a result:\n'
    '- The robot cannot adapt to uneven terrain in the lateral direction.\n'
    '- Side slopes or obstacles perpendicular to the walking direction cannot be navigated.\n'
    '- A 3-DOF leg (adding a lateral hip DOF) would be required for rough terrain locomotion.\n'
    'This is an intentional simplification for this project, acceptable on flat ground.'
)

pdf.subsection('Limitation 2: Trot Gait is Dynamically Unstable at Low Speeds')
pdf.body(
    'The trot gait maintains only 2 feet in contact at any time. This is dynamically stable '
    'only when the robot maintains sufficient forward speed. At low speed or when stationary:\n'
    '- The CoM projection lies on the support line (not inside a polygon).\n'
    '- Active balance control (not implemented here) would be required.\n'
    '- A walk gait (3-foot contact) is statically stable but slower and more complex to '
    'implement in practice. The simple open-loop gait assumed here has no feedback.'
)

pdf.subsection('Limitation 3 (Bonus): Rigid Body Assumption')
pdf.body(
    'The model assumes rigid links and ideal actuators. In practice:\n'
    '- Joint compliance and motor torque limits affect the real motion profile.\n'
    '- Foot-ground contact is modelled as a point, ignoring friction and compliance.\n'
    '- These simplifications are appropriate for first-order design but would require '
    'refinement in a real implementation.'
)


# -- References and Tools ------------------------------------------------------
pdf.add_page()
pdf.section('Tools and References')

pdf.subsection('Tools Used')
pdf.kv('CAD Visualization',  'Python 3.14 + Matplotlib 3D (mpl_toolkits.mplot3d)')
pdf.kv('Gait Calculation',   'Python 3.14 + NumPy + SciPy')
pdf.kv('Stability Analysis', 'SciPy ConvexHull + Matplotlib')
pdf.kv('Animation',          'Matplotlib FuncAnimation (saved as GIF via Pillow)')
pdf.kv('Report',             'Python fpdf2 library')

pdf.ln(3)
pdf.subsection('References')
pdf.body(
    '1. Raibert, M. et al. (2008). BigDog, the rough-terrain quadruped robot. '
    'IFAC Proceedings Volumes, 41(2), 10822-10825.\n\n'
    '2. Siciliano, B. and Sciavicco, L. (2009). Robotics: Modelling, Planning and Control. '
    'Springer.\n\n'
    '3. Gehring, C. et al. (2016). Practice Makes Perfect: An Optimization-Based Approach to '
    'Adaptive Legged Locomotion. IEEE Robotics and Automation Letters.\n\n'
    '4. Kajita, S. et al. (2003). Introduction to Humanoid Robotics. Springer Tracts '
    'in Advanced Robotics.\n\n'
    '5. Craig, J. J. (2005). Introduction to Robotics: Mechanics and Control. Pearson.'
)

pdf.ln(5)
pdf.subsection('Submission Contents')
pdf.body(
    '- Project_Report_Dhruv_Khanna.pdf  (this document)\n'
    '- Q1_Q2_robot_isometric.png        (Q1/Q2 - Isometric CAD view)\n'
    '- Q1_Q2_robot_front.png            (Q1/Q2 - Front view)\n'
    '- Q1_Q2_robot_side.png             (Q1/Q2 - Side view)\n'
    '- Q1_Q2_robot_top.png              (Q1/Q2 - Top view)\n'
    '- Q3_joint_limits.png              (Q3 - Joint limit diagram)\n'
    '- Q4_motion_simulation.gif         (Q4 - Animated motion simulation)\n'
    '- Q4_motion_snapshot.png           (Q4 - Static motion snapshot)\n'
    '- Q5_gait_calculation.png          (Q5 - Gait calculation plots)\n'
    '- Q6_stability_check.png           (Q6 - Support polygon analysis)\n'
    '- Q1_Q2_robot_visualization.py     (Source: Q1/Q2)\n'
    '- Q3_Q4_joint_motion.py            (Source: Q3/Q4)\n'
    '- Q5_gait_calculation.py           (Source: Q5)\n'
    '- Q6_stability_check.py            (Source: Q6)'
)


# -- Save ----------------------------------------------------------------------
pdf.output(REPORT)
print(f'  Saved: {REPORT}')
print('Report Done.')
